name: Running Code Coverage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:coverage

      - name: Commit to user repo(needed for deployment to vercel for free)
        run: |
        git clone --depth 1 https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Denisalik/ssad_frontend_deploy
        git add --all
        git reset -- .github
        git commit -m "pushing to deployment"
        git remote add origin https://github.com/Denisalik/ssad_frontend_deploy
        git push origin master

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}