name: Running Code Coverage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: Denisalik/ssad_frontend_deploy
          token: ${{ secrets.PAT_FOR_PUSH}}
          persist-credentials: false

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Commit to user repo(needed for deployment to vercel for free)
        run: |
          git config --local user.email "schegletovdenis@mail.ru"
          git config --local user.name Denisalik
          rm -r .github
          git add .
          git commit -m "pushing to deployment"
          git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
          git push --force --quiet https://Denisalik:$REPO_KEY@github.com/Denisalik/ssad_frontend_deploy.git HEAD:master

        env:
          REPO_KEY: ${{ secrets.PAT_FOR_PUSH }}
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:coverage


      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}